[package]
name = "git-monitor-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = { version = "0.17.2" }
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
structopt = "0.3"
