export type RepoState =
  | 'ApplyMailbox'
  | 'ApplyMailboxOrRebase'
  | 'Bisect'
  | 'CheeryPickSequence'
  | 'CherryPick'
  | 'Clean'
  | 'Merge'
  | 'Rebase'
  | 'RebaseInteractive'
  | 'RebaseMerge'
  | 'Revert'
  | 'RevertSequence'
