name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup-rust
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: git-monitor-backend
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: git-monitor-backend/prisma-cli
      - name: Run tests
        working-directory: ./git-monitor-backend
        run: |
          cargo prisma generate
          cargo check
